# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.3.2
_src_path: gh:algorandfoundation/algokit-python-template
author_email: 115161770+uhudo@users.noreply.github.com
author_name: uhudo
contract_name: hello_world
deployment_language: python
preset_name: production
project_name: certify-contracts

